---
- hosts: localhost
  vars:
    - s: "Name1:Value1,Name2:Value2,Name3:Value3"
    - nlayer: "[{% for sub in s.split(',') %}{{sub.split(':')}},{% endfor %}]"
  tasks:
	- name:
      - set_fact:
          nlayerdict: "{{ dict(nlayer) }}"
		
	  block:
		- debug:
			msg: "{{ dict(nlayer) }}"
		- name: Using dict2items
		  ansible.builtin.debug:
			msg: "{{ item.key }} - {{ item.value }}"
		  loop: "{{ nlayer }}"		
