---
- hosts: localhost
  vars:
    - s: "Name1:Value1,Name2:Value2,Name3:Value3"
    - nlayer: "[{% for sub in s.split(',') %}{{sub.split(':')}},{% endfor %}]"
  tasks:
    - debug:
        msg: "{{ dict(nlayer) }}"
